// The feed — every essay from the three streams, newest tending first.
// Dates come from src/data/dates.json (git-derived, regenerated by
// scripts/dates.mjs): "modified" is the honest signal in a tended garden,
// with "published" as the fallback.
import rss from "@astrojs/rss";
import { getCollection } from "astro:content";
import type { APIContext } from "astro";
import dates from "../data/dates.json";

const STREAMS = [
  { collection: "fieldNotes", path: "field-notes" },
  { collection: "workbench", path: "workbench" },
  { collection: "bodySpine", path: "body-spine" },
] as const;

export async function GET(context: APIContext) {
  const items = [];
  for (const stream of STREAMS) {
    const entries = await getCollection(stream.collection);
    for (const entry of entries) {
      const key = `${stream.path}/${entry.id}`;
      const d = (dates as Record<string, { published?: string; modified?: string }>)[key];
      const iso = d?.modified || d?.published;
      items.push({
        title: entry.data.title,
        description: entry.data.dek,
        link: `/${stream.path}/${entry.id}`,
        pubDate: iso ? new Date(iso) : new Date(0),
      });
    }
  }
  items.sort((a, b) => b.pubDate.getTime() - a.pubDate.getTime());

  return rss({
    title: "Enka Kanopi",
    description:
      "A canopy for a self in motion — essays on identity, craft, memory, and the body. Volume I · In Formation.",
    site: context.site!,
    items,
    // match the site-wide trailingSlash: 'never' convention
    trailingSlash: false,
  });
}
